settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: alistr # unique identifier
    name: ALIST 
    description: 'Web Lưu trữ Alist' # default=empty
    url: 'https://alisttr.top' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: koyeb.alistr
    name: BACKUP ALIST KOYEB
    description: 'Backup Alist Koyeb'
    url: 'https://koyeb.alisttr.top'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: glitch.alisttr.top
    name: BACKUP ALIST GLITCH
    description: 'Backup Alist Glitch'
    url: 'https://glitch.alisttr.top'
    method: GET
    expectStatus: 200

  - id: onedrive.alisttr.top
    name: ONEDRIVE INDEX
    description: 'Onedrive'
    url: 'https://onedrive.alisttr.top'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: ChatGPT
    name: CHATGPT NEXTWEB
    description: 'https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web'
    url: 'https://chatgpt.alisttr.top'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    
  - id: vaultwarden
    name: VAULTWARDEN
    description: 'https://github.com/dani-garcia/vaultwarden'
    url: 'https://ps.alisttr.top'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: next.alisttr.top
    name: NEXTCHAT Vercel
    description: 'https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web'
    url: 'https://next.alisttr.top'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: oneapi
    name: ONEAPI 
    description: 'https://github.com/songquanpeng/one-api'
    url: 'https://one-api-en-latest.onrender.com/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

