settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: alistr # unique identifier
    name: alisttr.top
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://alisttr.top' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: koyeb.alistr
    name: koyeb.alisttr.top
    description: 'Built for anything connected to the Internet.'
    url: 'https://koyeb.alisttr.top'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: glitch.alisttr.top
    name: glitch.alisttr.top
    url: 'https://glitch.alisttr.top/'
    method: GET
    expectStatus: 200

  - id: onedrive.alisttr.top
    name: https://onedrive.alisttr.top/
    description: 'Built for anything connected to the Internet.'
    url: 'https://onedrive.alisttr.top'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
